### ISSUE TITLE
Unifi Documentation - Map VLAN Only Networks

### ISSUE THREAD

**Issue by Danpoulter97** [lwhitelock/HuduAutomation#25]
Just wondering how easy it would be to map VLAN Only networks from Unifi as we don't tend to use the USGs but have the switches so the networks are added into our controller as VLAN only networks.

**Comment by jn1102** [comment]
I came across this recently that seems to answer your question.

https://www.reddit.com/r/msp/comments/xd79kq/documenting_unifi_wireless_network_passwords/

**Comment by Danpoulter97** [comment]
Perfect, just what I needed.

Thanks for the update!
