### ISSUE TITLE
Completed Tickets

### ISSUE THREAD

**Issue by jlinx2** [lwhitelock/HuduAutomation#3]
If a company has an open ticket in AutoTask when the script is run the first time, it creates the MagicDash button.   If later that same company has all their tickets closed, the script does not update the MagicDash button to not show show that there are 0 tickets for that company queue.  Is there a command that will clear all MagicDash buttons prior to running this script?

**Comment by lwhitelock** [comment]
I've updated the script. There was an if check to make sure it got at least one ticket before running the code that populated the magic dash. I've updated it now so that there is an else which just sets a no tickets magic dash if there are no open tickets.
